version: "3.9"

services:
  ffmpeg-api:
    build: .
    container_name: ffmpeg-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Santo_Domingo
    volumes:
      - ./uploads:/app/uploads        # Carpeta temporal para archivos
